# Generated by Django 5.1 on 2024-08-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('fault_detection', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('school', models.CharField(choices=[('SC', 'school of science'), ('BIZ', 'business education'), ('ST', 'school of technical'), ('VC', 'vocation'), ('CE', 'continue education'), ('CM', 'computer'), ('FA', 'Art and fine Art'), ('EC', 'Early Childhood'), ('OR', 'other')], max_length=200, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=100, unique=True)),
                ('confirm_password', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
