# Generated by Django 5.1 on 2024-08-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='reporter',
            new_name='name',
        ),
    ]
