# Generated by Django 5.1 on 2024-08-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_issue_date_reported_register_campus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
