# Generated by Django 5.1 on 2024-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='name',
        ),
        migrations.AddField(
            model_name='issue',
            name='campus',
            field=models.CharField(choices=[('C1', 'campus1'), ('C2', 'campus2')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='staff',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='fault_detection',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
