# Generated by Django 5.1 on 2024-08-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_userfeedback_location_userfeedback_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='location',
            new_name='fault_location',
        ),
    ]
