# Generated by Django 5.1 on 2024-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_issue_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
