# Generated by Django 5.1 on 2024-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_userfeedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fault_detection',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
