# Generated by Django 5.1 on 2024-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_issue_fault_detection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fault_detection',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
