# Generated by Django 5.1 on 2024-09-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_issue_fault_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='campus',
            field=models.CharField(choices=[('campus1', 'campus1'), ('campus2', 'campus2')], max_length=10, null=True),
        ),
    ]
