# Generated by Django 5.1 on 2024-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_issue_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('Unattended', 'Unattended'), ('Pending', 'Pending'), ('Rectified', 'Rectified')], max_length=10, null=True),
        ),
    ]
