# Generated by Django 5.1 on 2024-08-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
